-- ============================================================================
-- snacks.nvim — Utility plugin with image support for SwiftUI / UIKit previews
-- ============================================================================
-- WHAT IT DOES:
--   snacks.nvim is a collection of small QoL modules. We install it here solely
--   for the "image" snack, which renders images inside Neovim's terminal buffers.
--   xcodebuild.nvim uses this to display live SwiftUI / UIKit / AppKit previews
--   generated by the xcodebuild-nvim-preview Swift package.
--
-- PREVIEW WORKFLOW:
--   1. Add the xcodebuild-nvim-preview Swift Package to your Xcode project
--      (https://github.com/wojciech-kulik/xcodebuild-nvim-preview)
--   2. Call XcodebuildNvimPreview.setup(view: MyPreviewView()) in your App delegate
--      or @main SwiftUI App body.
--   3. In Neovim, run :XcodebuildPreviewGenerateAndShow
--   4. The app builds, launches in background, captures the view, and sends the
--      PNG back to Neovim where snacks.nvim renders it in a split window.
--
-- DEPENDENCIES:
--   • A terminal that supports images (Kitty, WezTerm, iTerm2, Ghostty, etc.)
--   • xcodebuild-nvim-preview Swift package added to your project
--
-- NOTE:
--   If your terminal does not support images, previews will silently fail or
--   show raw ANSI escape sequences. Test with :lua Snacks.image.test()
-- ============================================================================

return {
  {
    'folke/snacks.nvim',
    priority = 1000,
    lazy = false,
    opts = {
      -- Enable only the image module. Other snacks (notifier, picker, etc.)
      -- are disabled to keep startup fast and avoid conflicts with existing
      -- plugins (telescope, fidget, etc.).
      image = {
        enabled = true,
      },

      -- Disable everything else we don't need.
      bigfile = { enabled = false },
      dashboard = { enabled = false },
      indent = { enabled = false },
      input = { enabled = false },
      notifier = { enabled = false },
      picker = { enabled = false },
      quickfile = { enabled = false },
      scope = { enabled = false },
      scroll = { enabled = false },
      statuscolumn = { enabled = false },
      words = { enabled = false },
    },
  },
}
